### PR TITLE
Different general improvements and fixes 

### PR DESCRIPTION
**Pull request by emmanuelm41**

### CODE REVIEW

**Comment by fbeutin-ledger** [comment]
Hello @emmanuelm41 , can you please add the guidelines enforcer to the app ?

**Comment by emmanuelm41** [comment]
> Hello @emmanuelm41 , can you please add the guidelines enforcer to the app ?

What do you mean by that? You mean a brief description on the PR?

**Comment by emmanuelm41** [comment]
@fbeutin-ledger I have added the ci workflows you mentioned. However, some of them will fail as the plugin is not up to date with the boilerplate project. Doing so will require some extra effort.

**Comment by fbeutin-ledger** [comment]
Hi @emmanuelm41 , I believe this PR that handles the Stax porting bumps the SDK version
https://github.com/LedgerHQ/app-plugin-rarible/pull/4

**Comment by emmanuelm41** [comment]
@fbeutin-ledger sorry his PR got closed. I changed the default branch name to develop. I created a new PR here 
https://github.com/LedgerHQ/app-plugin-rarible/pull/5

**Pull request closed without merging**
